### ISSUE TITLE
I don't understand how this works

### ISSUE THREAD

**Issue by Analog98** [gameboy9/7thSagaRando#5]
I have no idea how to actually get the randomizer to work. When I launch the Executable, all of the randomization dropdown bars instantly reset to "no randomization" when I select them. I downloaded the newest .EXE (3.5.1, I believe), as well as the source code and the master file thing, but I don't know what to do next. I'm very much not tech savvy and could really use some help figuring this out, thanks!

**Comment by gameboy9** [comment]
I think you have to browse for the ROM, set the flags, then hit the randomize button... I think that's all you have to do.  Make sure the checksums match, or you might not have a randomized ROM.

**Comment by michael-simon** [comment]
This appears to be a copy of https://github.com/gameboy9/7thSagaRando/issues/6 / you seem to be having the same issue, I put a reproduction there.

@Analog98 It's possible to work around it by using one of the preset options (like 'super-speedrunish') to get the flags to change, and then the drop-down boxes behave as expected.

**Comment by gameboy9** [comment]
Fixed in release 3.5.2.
