### ISSUE TITLE
Randomizer not working

### ISSUE THREAD

**Issue by Cylian997** [gameboy9/7thSagaRando#6]
I have the right rom with the right checksum but when I click on an option to randomize something the program switches back to "no XXXX".

**Comment by michael-simon** [comment]
To clarify and reproduce:
1) Download the current version of the Randomizer (3.5.1, displaying as 3.5).
2) Run it from a directory you have never run it from before, to make sure that it doesn't have any pre-set configuration as to what the flags should be.
3) Attempt to change any of the randomizer options that are drop-down boxes: they will immediately reset to their default value.

@Cylian997 Until this gets fixed, you can work around this by going over to the 'presets' section, and picking a preset. Once you've got something that isn't the defaults in, the program seems to work as expected.

**Comment by Cylian997** [comment]
@michael-simon 

Everything you stated was correct and when I generated a "superspeenrun-ish" rom, then it decided to work properly by allowing me to change the flags.

Thanks!

**Comment by gameboy9** [comment]
Fixed in release 3.5.2.
